# Generated by Django 4.2.19 on 2025-03-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marks",
            name="id",
            field=models.IntegerField(
                editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="id",
            field=models.IntegerField(
                editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="id",
            field=models.IntegerField(
                editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
