# Generated by Django 4.2.19 on 2025-03-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_app", "0002_alter_marks_id_alter_student_id_alter_subject_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="roll_no",
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
