# Generated by Django 4.2.19 on 2025-03-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_app", "0003_alter_student_roll_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marks",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
