# Generated by Django 4.2.19 on 2025-03-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_app", "0004_alter_marks_id_alter_student_id_alter_subject_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField(null="True")),
            ],
        ),
    ]
